module.exports = {
    tags: ['API',
    'Accessibility',
    'Books',
    'CI/CD',
    'Chart',
    'Color',
    'Courses',
    'Data Visualization',
    'Databases',
    'Design News',
    'Design Systems',
    'Design Tools',
    'Editing',
    'Formating',
    'git',
    'Icons',
    'Illustrations',
    'Inspiration',
    'Migration',
    'Mockup Tools',
    'Newsletter',
    'npm',
    'Podcasts',
    'Prototyping Tools',
    'Query',
    'Resources',
    'SEO',
    'Stock Photos',
    'Testing',
    'Typography',
    'Wireframing']
};